/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as EmailRouteImport } from './routes/email'
import { Route as CvRevampRouteImport } from './routes/cv-revamp'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AutoapplyRouteImport } from './routes/autoapply'
import { Route as IndexRouteImport } from './routes/index'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRevampRoute = CvRevampRouteImport.update({
  id: '/cv-revamp',
  path: '/cv-revamp',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoapplyRoute = AutoapplyRouteImport.update({
  id: '/autoapply',
  path: '/autoapply',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/autoapply': typeof AutoapplyRoute
  '/chat': typeof ChatRoute
  '/cv-revamp': typeof CvRevampRoute
  '/email': typeof EmailRoute
  '/jobs': typeof JobsRoute
  '/meetings': typeof MeetingsRoute
  '/research': typeof ResearchRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/autoapply': typeof AutoapplyRoute
  '/chat': typeof ChatRoute
  '/cv-revamp': typeof CvRevampRoute
  '/email': typeof EmailRoute
  '/jobs': typeof JobsRoute
  '/meetings': typeof MeetingsRoute
  '/research': typeof ResearchRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/autoapply': typeof AutoapplyRoute
  '/chat': typeof ChatRoute
  '/cv-revamp': typeof CvRevampRoute
  '/email': typeof EmailRoute
  '/jobs': typeof JobsRoute
  '/meetings': typeof MeetingsRoute
  '/research': typeof ResearchRoute
  '/tasks': typeof TasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/autoapply'
    | '/chat'
    | '/cv-revamp'
    | '/email'
    | '/jobs'
    | '/meetings'
    | '/research'
    | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/autoapply'
    | '/chat'
    | '/cv-revamp'
    | '/email'
    | '/jobs'
    | '/meetings'
    | '/research'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/autoapply'
    | '/chat'
    | '/cv-revamp'
    | '/email'
    | '/jobs'
    | '/meetings'
    | '/research'
    | '/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutoapplyRoute: typeof AutoapplyRoute
  ChatRoute: typeof ChatRoute
  CvRevampRoute: typeof CvRevampRoute
  EmailRoute: typeof EmailRoute
  JobsRoute: typeof JobsRoute
  MeetingsRoute: typeof MeetingsRoute
  ResearchRoute: typeof ResearchRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv-revamp': {
      id: '/cv-revamp'
      path: '/cv-revamp'
      fullPath: '/cv-revamp'
      preLoaderRoute: typeof CvRevampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoapply': {
      id: '/autoapply'
      path: '/autoapply'
      fullPath: '/autoapply'
      preLoaderRoute: typeof AutoapplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutoapplyRoute: AutoapplyRoute,
  ChatRoute: ChatRoute,
  CvRevampRoute: CvRevampRoute,
  EmailRoute: EmailRoute,
  JobsRoute: JobsRoute,
  MeetingsRoute: MeetingsRoute,
  ResearchRoute: ResearchRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
